#ifndef MICROPY_INCLUDED_ESP32_MODEPUCK2_H
#define MICROPY_INCLUDED_ESP32_MODEPUCK2_H

#define EPUCK2_API_MAJOR_VERSION 1
#define EPUCK2_API_MINOR_VERSION 0

#endif // MICROPY_INCLUDED_ESP32_MODEPUCK2_H
